all:
  children:
    cloudera_manager:
      hosts:
        cm_host:
          ansible_host: ip-172-31-25-226.eu-north-1.compute.internal
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/id_rsa

    master_nodes:
      hosts:
        master1:
          ansible_host: ip-172-31-25-226.eu-north-1.compute.internal

    worker_nodes:
      hosts:
        worker1:
          ansible_host: ip-172-31-31-151.eu-north-1.compute.internal

  vars:
    ansible_connection: ssh
    ansible_user: ec2-user
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_become: yes
    ansible_become_method: sudo

