name: Ansible Pre-Req Run QCB

on:
  workflow_dispatch:
    inputs:
      branch:
      selected_roles:
        description: "Select the Ansible roles to execute"
        required: true
        type: choice
        default: ports_check_role
        options:
          - network_connectivity_check
          - os_services_check
          - packages_check
          - ports_check_role

jobs:
  run-ansible-playbook:
    runs-on: self-hosted  # This will run on your GitHub Runner Server

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}  # Checkout the selected branch

#      - name: Set up Ansible
#        run: |
#          sudo apt update -y
#          sudo apt install -y ansible

      - name: Create Ansible Vault Password File
        run: echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > ~/.vault_pass
        shell: bash

      - name: Run Selected Ansible Role
        run: |
          ansible-playbook -i inventory/inventory.yml playbook.yml --extra-vars "selected_role=${{ github.event.inputs.selected_roles }}" --vault-password-file ~/.vault_pass
        shell: bash

      - name: Generate Advanced Workflow Diagram
        run: |
          echo '```mermaid' >> $GITHUB_STEP_SUMMARY
          echo 'graph TD;' >> $GITHUB_STEP_SUMMARY
          echo '    A[Set up Job] -->|Clone Repo| B[Checkout Repository]' >> $GITHUB_STEP_SUMMARY
          echo '    B -->|Secrets Loaded| C[Create Ansible Vault Password File]' >> $GITHUB_STEP_SUMMARY
          echo '    C -->|Start Ansible| D[Run Selected Ansible Role]' >> $GITHUB_STEP_SUMMARY
          echo '    D -->|Cleanup| E[Post Checkout Repository]' >> $GITHUB_STEP_SUMMARY
          echo '    E -->|Complete| F[Complete Job]' >> $GITHUB_STEP_SUMMARY
          echo '    D -->|Errors?| G[Debug & Retry]' >> $GITHUB_STEP_SUMMARY
          echo '    G -->|Fix Issues| D' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

